services:
  main-service:
    container_name: nestjs-main-service
    build:
      context: .
      dockerfile: apps/main/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
        - action: rebuild
          path: apps/main/
    depends_on:
      - auth-service
      - user-service
    network_mode: host

  auth-service:
    container_name: nestjs-auth-service
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
        - action: rebuild
          path: apps/auth/
    depends_on:
      - user-service
    network_mode: host

  user-service:
    container_name: nestjs-user-service
    build:
      context: .
      dockerfile: apps/user/Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
        - action: rebuild
          path: apps/user/
    network_mode: host
