import { Injectable, Logger } from '@nestjs/common';
import {
  UNLIMITED,
  PlanLimitKeys,
  BillingEventPatterns,
} from 'apps/constants';
import { SubscriptionService } from './subscription.service';
import { LIFETIME_PERIOD } from '../entities/subscription-usage.entity';
import { ProcessedEventRepository } from '../../infrastructure/repository/processed-event.repository';
import { SubscriptionUsageRepository } from '../../infrastructure/repository/subscription-usage.repository';

/** Usage event payload shared by every BILLING_EVT_* emission. */
export interface UsageEvent {
  /** Unique id for at-least-once dedup (uuid generated by the emitter). */
  eventId?: string;
  organizationId: string;
  /** Bytes for file events, count for batched events; defaults to 1. */
  quantity?: number;
  bytes?: number;
}

export interface LimitCheckInput {
  organizationId: string;
  /** A PlanLimitKeys value. */
  limitKey: string;
  /** How much the pending operation would add (counter units). */
  delta?: number;
  /**
   * Authoritative current value supplied by the caller (e.g. the gateway's
   * live property count). Falls back to the event-sourced counter.
   */
  current?: number;
}

export interface LimitCheckResult {
  allowed: boolean;
  reason?: 'limit_reached' | 'subscription_inactive';
  limitKey: string;
  limit?: number;
  current?: number;
  code?: 'PROPERTY_LIMIT_EXCEEDED' | 'PLAN_LIMIT_REACHED' | 'SUBSCRIPTION_INACTIVE';
  currentPlan?: string;
  currentPlanName?: string;
  upgradeAvailable?: boolean;
}

const GB = 1024 * 1024 * 1024;

/** Gauges live forever; meters are keyed by month and reset naturally. */
const GAUGES = new Set([
  'properties',
  'members',
  'storageBytes',
  'activeListings',
]);

/** limitKey → counter that measures it. */
const LIMIT_COUNTERS: Record<string, string> = {
  [PlanLimitKeys.PROPERTIES]: 'properties',
  [PlanLimitKeys.MEMBERS]: 'members',
  [PlanLimitKeys.ACTIVE_LISTINGS]: 'activeListings',
  [PlanLimitKeys.STORAGE_GB]: 'storageBytes',
  [PlanLimitKeys.API_REQUESTS_PER_MONTH]: 'apiRequests',
  [PlanLimitKeys.FILE_UPLOADS_PER_MONTH]: 'fileUploads',
  [PlanLimitKeys.LEADS_PER_MONTH]: 'leads',
  [PlanLimitKeys.CUSTOM_DOMAINS]: 'customDomains',
  [PlanLimitKeys.INTEGRATIONS]: 'integrations',
};

function limitErrorCode(limitKey: string): 'PROPERTY_LIMIT_EXCEEDED' | 'PLAN_LIMIT_REACHED' {
  return limitKey === PlanLimitKeys.PROPERTIES
    ? 'PROPERTY_LIMIT_EXCEEDED'
    : 'PLAN_LIMIT_REACHED';
}

@Injectable()
export class UsageService {
  private readonly logger = new Logger(UsageService.name);

  constructor(
    private readonly usageRepository: SubscriptionUsageRepository,
    private readonly processedEvents: ProcessedEventRepository,
    private readonly subscriptionService: SubscriptionService,
  ) {}

  /* ------------------------------------------------------- event intake */

  /**
   * Apply one domain event to the counters. Deduplicated by eventId so
   * at-least-once delivery (fire-and-forget emit) cannot double count.
   */
  async recordEvent(pattern: string, event: UsageEvent): Promise<void> {
    if (!event?.organizationId) return;
    const fresh = await this.processedEvents.claim(
      event.eventId,
      pattern,
    );
    if (!fresh) return;

    const quantity = event.quantity ?? 1;
    const organizationId = event.organizationId;

    switch (pattern) {
      case BillingEventPatterns.ORGANIZATION_CREATED:
        // Bootstrap the subscription and seed the founding member gauge.
        await this.subscriptionService.getOverview(organizationId);
        await this.setGauges(organizationId, { members: 1 });
        return;
      case BillingEventPatterns.PROPERTY_CREATED:
        return this.inc(organizationId, 'properties', quantity);
      case BillingEventPatterns.PROPERTY_DELETED:
        return this.inc(organizationId, 'properties', -quantity);
      case BillingEventPatterns.MEMBER_ADDED:
        return this.inc(organizationId, 'members', quantity);
      case BillingEventPatterns.MEMBER_REMOVED:
        return this.inc(organizationId, 'members', -quantity);
      case BillingEventPatterns.FILE_UPLOADED:
        await this.inc(organizationId, 'storageBytes', event.bytes ?? 0);
        return this.inc(organizationId, 'fileUploads', quantity);
      case BillingEventPatterns.FILE_DELETED:
        return this.inc(organizationId, 'storageBytes', -(event.bytes ?? 0));
      case BillingEventPatterns.API_USAGE:
        return this.inc(organizationId, 'apiRequests', quantity);
      case BillingEventPatterns.LEAD_CAPTURED:
        return this.inc(organizationId, 'leads', quantity);
      default:
        this.logger.warn(`Unknown usage event pattern: ${pattern}`);
    }
  }

  /* --------------------------------------------------------------- reads */

  /**
   * Current usage joined with the plan's limits — the payload behind the
   * billing dashboard's meters. Counters are event-sourced (cheap reads);
   * the gateway periodically pushes authoritative values via syncUsage.
   */
  async getUsage(organizationId: string) {
    const [counters, entitlements] = await Promise.all([
      this.usageRepository.countersFor(organizationId, this.monthPeriod()),
      this.subscriptionService.getEntitlements(organizationId),
    ]);

    const metrics = Object.entries(LIMIT_COUNTERS).map(
      ([limitKey, counterKey]) => {
        const isStorage = limitKey === PlanLimitKeys.STORAGE_GB;
        const rawUsed = counters[counterKey] ?? 0;
        const limit = entitlements.limits?.[limitKey];
        return {
          limitKey,
          /** Storage reported in bytes; the UI formats it. */
          used: rawUsed,
          limit: limit ?? null,
          unlimited: limit === UNLIMITED,
          monthly: !GAUGES.has(counterKey),
          remaining:
            limit === undefined || limit === UNLIMITED
              ? null
              : Math.max(
                  (isStorage ? limit * GB : limit) - rawUsed,
                  0,
                ),
        };
      },
    );

    return {
      organizationId,
      period: this.monthPeriod(),
      metrics,
      syncedAt:
        (await this.usageRepository.find(organizationId, LIFETIME_PERIOD))
          ?.syncedAt ?? null,
    };
  }

  /* -------------------------------------------------------- enforcement */

  /**
   * Server-side plan enforcement. Suspended/expired subscriptions fail every
   * check; otherwise the pending delta is compared against the plan limit.
   * Frontend validation is cosmetic — this is the authority.
   */
  async checkLimit(input: LimitCheckInput): Promise<LimitCheckResult> {
    const entitlements = await this.subscriptionService.getEntitlements(
      input.organizationId,
    );

    if (!entitlements.isOperational) {
      return {
        allowed: false,
        reason: 'subscription_inactive',
        code: 'SUBSCRIPTION_INACTIVE',
        limitKey: input.limitKey,
        currentPlan: entitlements.planSlug,
        currentPlanName: entitlements.planName,
        upgradeAvailable: true,
      };
    }

    const limit = entitlements.limits?.[input.limitKey];
    // No limit configured for this plan → unconstrained.
    if (limit === undefined || limit === UNLIMITED) {
      return { allowed: true, limitKey: input.limitKey, limit };
    }

    const counterKey = LIMIT_COUNTERS[input.limitKey] ?? input.limitKey;
    const counters = await this.usageRepository.countersFor(
      input.organizationId,
      this.monthPeriod(),
    );
    const current = input.current ?? counters[counterKey] ?? 0;
    const delta = input.delta ?? 1;

    // Storage limits are configured in GB but measured in bytes.
    const effectiveLimit =
      input.limitKey === PlanLimitKeys.STORAGE_GB ? limit * GB : limit;

    const allowed = current + delta <= effectiveLimit;
    return {
      allowed,
      reason: allowed ? undefined : 'limit_reached',
      limitKey: input.limitKey,
      limit: effectiveLimit,
      current,
      code: allowed ? undefined : limitErrorCode(input.limitKey),
      currentPlan: entitlements.planSlug,
      currentPlanName: entitlements.planName,
      upgradeAvailable: !allowed,
    };
  }

  /** Overwrite gauges with authoritative values from the gateway. */
  async syncUsage(
    organizationId: string,
    gauges: Record<string, number>,
  ): Promise<void> {
    const safe: Record<string, number> = {};
    for (const [key, value] of Object.entries(gauges)) {
      if (GAUGES.has(key) && Number.isFinite(value)) {
        safe[key] = Math.max(0, value);
      }
    }
    if (Object.keys(safe).length === 0) return;
    await this.usageRepository.setCounters(
      organizationId,
      LIFETIME_PERIOD,
      safe,
    );
  }

  /* ------------------------------------------------------------- helpers */

  private async inc(
    organizationId: string,
    counter: string,
    delta: number,
  ): Promise<void> {
    if (!delta) return;
    const period = GAUGES.has(counter) ? LIFETIME_PERIOD : this.monthPeriod();
    await this.usageRepository.increment(
      organizationId,
      period,
      counter,
      delta,
    );
  }

  private async setGauges(
    organizationId: string,
    gauges: Record<string, number>,
  ): Promise<void> {
    await this.usageRepository.setCounters(
      organizationId,
      LIFETIME_PERIOD,
      gauges,
    );
  }

  private monthPeriod(date = new Date()): string {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
  }
}
