FROM node:20-alpine

WORKDIR /usr/src/app

# Copy package files first to leverage cache
COPY package*.json ./

# Install all dependencies (including dev)
RUN npm install

# We'll mount the source code in docker-compose
CMD ["npm", "run", "start:dev", "main"] 